In [99]:
from tensorflow.keras.preprocessing.text import one_hot



In [100]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [101]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [102]:
## Define the vocabulary size
voc_size=10000

In [103]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4150, 6785, 1070, 5789],
 [4150, 6785, 1070, 1506],
 [4150, 2708, 1070, 2052],
 [965, 4359, 314, 4046, 2300],
 [965, 4359, 314, 4046, 9876],
 [266, 4150, 6420, 1070, 3793],
 [7218, 709, 8874, 4046]]

In [104]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [105]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4150 6785 1070 5789]
 [   0    0    0    0 4150 6785 1070 1506]
 [   0    0    0    0 4150 2708 1070 2052]
 [   0    0    0  965 4359  314 4046 2300]
 [   0    0    0  965 4359  314 4046 9876]
 [   0    0    0  266 4150 6420 1070 3793]
 [   0    0    0    0 7218  709 8874 4046]]


In [106]:
## feature representation
dim=10

In [107]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [108]:
model.predict(embedded_docs[0][0])

IndexError: tuple index out of range

In [86]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (8, 10)                │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [87]:
embedded_docs[0]

array([   0,    0,    0,    0, 4150, 6785, 1070, 5789], dtype=int32)

In [88]:
# model.predict(embedded_docs[0])